apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-handlers-pvc
  namespace: inference-benchmark
spec:
  accessModes:
    - ReadWriteOnce   # one node can mount read-write; inference pods on same node read it
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
